/// <reference path="../../lib/tpl.d.ts" />
// AUTO-GENERATED by tpl — do not edit
// Source: src/shared/assistant.tpl.md
// Syntax:
//   {{var}}               required variable (string by default)
//   {{var:type}}          typed: string | number | boolean | string[]
//   {{var|default}}       optional — uses default when omitted
//   {{#if var}}...{{/if}} conditional block — condition-only vars are optional booleans
//   {{> ./path}}          relative partial — vars-less partials auto-render; vars partials become nested interface fields
// Docs: https://github.com/timurkr/tpl

import { renderTemplate } from "the-prompting-library/runtime";
import TEMPLATE from "./assistant.tpl.md" with { type: "text" };
import { buildSharedBasePersonaPrompt } from "./base-persona.tpl.gen.js";
import { buildSharedOutputFormatPrompt } from "./output-format.tpl.gen.js";

/**
 * Full assistant persona with configurable tone and output format
 * @source src/shared/assistant.tpl.md
 */
export interface SharedAssistantVariables {
  tone?: string;
}

export function buildSharedAssistantPrompt(vars: SharedAssistantVariables): string {
  return renderTemplate(TEMPLATE, vars, { "persona": buildSharedBasePersonaPrompt(), "output": buildSharedOutputFormatPrompt() });
}
