/// <reference path="../../lib/tpl.d.ts" />
// AUTO-GENERATED by tpl — do not edit
// Source: src/shared/assistant.tpl.md
// Syntax:
//   {{var}}               required variable (string by default)
//   {{var:type}}          typed: string | number | boolean | string[]
//   {{var|default}}       optional — uses default when omitted
//   {{#if var}}...{{/if}} conditional block — condition-only vars are optional booleans
//   {{#switch v}}...{{/switch}} first matching {{#case "x"}} / {{#case 'x'}} / {{#case x}} ... {{/case}}, else {{#default}}...{{/default}}
//   {{> ./path}}          relative partial — vars-less partials auto-render; vars partials become nested interface fields
// Docs: https://github.com/timurkr/tpl

import { renderTemplate } from "the-prompting-library/runtime";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSharedBasePersonaPrompt } from "./base-persona.tpl.gen.js";
import { buildSharedOutputFormatPrompt } from "./output-format.tpl.gen.js";

const TEMPLATE = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "./assistant.tpl.md"), "utf8");

/**
 * Full assistant persona with configurable tone and output format
 * @source src/shared/assistant.tpl.md
 */
export interface SharedAssistantVariables {
  tone?: string;
}

export function buildSharedAssistantPrompt(vars: SharedAssistantVariables): string {
  return renderTemplate(TEMPLATE, vars, { "persona": buildSharedBasePersonaPrompt(), "output": buildSharedOutputFormatPrompt() });
}
