/// <reference path="../../lib/tpl.d.ts" />
// AUTO-GENERATED by tpl — do not edit
// Source: src/shared/output-format.tpl.md
// Syntax:
//   {{var}}               required variable (string by default)
//   {{var:type}}          typed: string | number | boolean | string[]
//   {{var|default}}       optional — uses default when omitted
//   {{#if var}}...{{/if}} conditional block — condition-only vars are optional booleans
//   {{> name}}            partial — vars-less partials auto-render; vars partials become nested interface fields
// Docs: https://github.com/timurkr/tpl

import { renderTemplate } from "the-prompting-library/runtime";
import TEMPLATE from "./output-format.tpl.md" with { type: "text" };

/**
 * @source src/shared/output-format.tpl.md
 */
export interface OutputFormatVariables {}

export function buildOutputFormatPrompt(): string {
  return renderTemplate(TEMPLATE, {});
}
