/// <reference path="../../lib/tpl.d.ts" />
// AUTO-GENERATED by tpl — do not edit
// Source: src/shared/response-style.tpl.md
// Syntax:
//   {{var}}               required variable (string by default)
//   {{var:type}}          typed: string | number | boolean | string[]
//   {{var|default}}       optional — uses default when omitted
//   {{#if var}}...{{/if}} conditional block — condition-only vars are optional booleans
//   {{#switch v}}...{{/switch}} first matching {{#case "x"}} / {{#case 'x'}} / {{#case x}} ... {{/case}}, else {{#default}}...{{/default}}
//   {{> ./path}}          relative partial — vars-less partials auto-render; vars partials become nested interface fields
// Docs: https://github.com/timurkr/tpl

import { renderTemplate } from "the-prompting-library/runtime";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const TEMPLATE = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "./response-style.tpl.md"), "utf8");

/**
 * Response style selected by a switch-only variable
 * @source src/shared/response-style.tpl.md
 */
export type SharedResponseStyleStyle = "concise" | "detailed" | "executive";

export interface SharedResponseStyleVariables {
  style?: SharedResponseStyleStyle;
}

export function buildSharedResponseStylePrompt(vars: SharedResponseStyleVariables): string {
  return renderTemplate(TEMPLATE, vars);
}
