/// <reference path="../../../lib/tpl.d.ts" />
// AUTO-GENERATED by tpl — do not edit
// Source: src/features/search/search-query.tpl.md
// Syntax:
//   {{var}}               required variable (string by default)
//   {{var:type}}          typed: string | number | boolean | string[]
//   {{var|default}}       optional — uses default when omitted
//   {{#if var}}...{{/if}} conditional block — condition-only vars are optional booleans
//   {{#switch v}}...{{/switch}} first matching {{#case "x"}} / {{#case 'x'}} / {{#case x}} ... {{/case}}, else {{#default}}...{{/default}}
//   {{> ./path}}          relative partial — vars-less partials auto-render; vars partials become nested interface fields
// Docs: https://github.com/timurkr/tpl

import { renderTemplate } from "the-prompting-library/runtime";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { buildSharedBasePersonaPrompt } from "../../shared/base-persona.tpl.gen.js";

const TEMPLATE = readFileSync(fileURLToPath(new URL("./search-query.tpl.md", import.meta.url)), "utf8");

/**
 * Semantic search query rewriter
 * @source src/features/search/search-query.tpl.md
 */
export interface SearchSearchQueryVariables {
  userQuery: string;
  contextDescription: string;
}

export function buildSearchSearchQueryPrompt(vars: SearchSearchQueryVariables): string {
  return renderTemplate(TEMPLATE, vars, { "persona": buildSharedBasePersonaPrompt() });
}
