// AUTO-GENERATED by tpl — do not edit
// Generated: 2026-04-24T09:44:41.572Z | 8 prompts

export * from "./assistant";
export * from "./basePersona";
export * from "./outputFormat";
export * from "./passwordReset";
export * from "./welcomeEmail";
export * from "./searchQuery";
export * from "./ticketClassifier";
export * from "./ticketSummary";

import { buildAssistantPrompt } from "./assistant";
import { buildBasePersonaPrompt } from "./basePersona";
import { buildOutputFormatPrompt } from "./outputFormat";
import { buildPasswordResetPrompt } from "./passwordReset";
import { buildWelcomeEmailPrompt } from "./welcomeEmail";
import { buildSearchQueryPrompt } from "./searchQuery";
import { buildTicketClassifierPrompt } from "./ticketClassifier";
import { buildTicketSummaryPrompt } from "./ticketSummary";

/**
 * All prompt builder functions, keyed by their short name.
 *
 * @example
 * import { prompts } from "./lib/prompts";
 * const text = prompts.summarize({ topic: "AI", wordCount: "50" });
 */
export const prompts = {
  assistant: buildAssistantPrompt,
  basePersona: buildBasePersonaPrompt,
  outputFormat: buildOutputFormatPrompt,
  passwordReset: buildPasswordResetPrompt,
  welcomeEmail: buildWelcomeEmailPrompt,
  searchQuery: buildSearchQueryPrompt,
  ticketClassifier: buildTicketClassifierPrompt,
  ticketSummary: buildTicketSummaryPrompt,
} as const;

/**
 * Render any prompt by name at runtime.
 * Useful when the template name comes from config or user input.
 *
 * @example
 * renderPrompt("summarize", { topic: "AI", wordCount: "50" });
 */
export function renderPrompt(
  name: keyof typeof prompts,
  vars: Record<string, unknown> = {}
): string {
  return (prompts[name] as (v: Record<string, unknown>) => string)(vars);
}
