// AUTO-GENERATED by tpl — do not edit
// Source: src/features/search/search-query.tpl.md
// Syntax:
//   {{var}}               required variable (string by default)
//   {{var:type}}          typed: string | number | boolean | string[]
//   {{var|default}}       optional — uses default when omitted
//   {{#if var}}...{{/if}} conditional block — omitted when var is falsy
//   {{> name}}            partial — vars-less partials auto-render; vars partials become nested interface fields
// Docs: https://github.com/timurkr/tpl

import { renderTemplate } from "the-prompting-library/runtime";
import TEMPLATE from "../../src/features/search/search-query.tpl.md" with { type: "text" };
import { buildBasePersonaPrompt } from "./basePersona";

/**
 * Semantic search query rewriter
 * @source src/features/search/search-query.tpl.md
 */
export interface SearchQueryVariables {
  userQuery: string;
  contextDescription: string;
}

export function buildSearchQueryPrompt(vars: SearchQueryVariables): string {
  return renderTemplate(TEMPLATE, vars, { basePersona: buildBasePersonaPrompt() });
}
