/// <reference path="../../../lib/tpl.d.ts" />
// AUTO-GENERATED by tpl — do not edit
// Source: src/features/auth/onboarding-sequence.tpl.md
// Syntax:
//   {{var}}               required variable (string by default)
//   {{var:type}}          typed: string | number | boolean | string[]
//   {{var|default}}       optional — uses default when omitted
//   {{#if var}}...{{/if}} conditional block — condition-only vars are optional booleans
//   {{> ./path}}          relative partial — vars-less partials auto-render; vars partials become nested interface fields
// Docs: https://github.com/timurkr/tpl

import { renderTemplate } from "the-prompting-library/runtime";
import TEMPLATE from "./onboarding-sequence.tpl.md" with { type: "text" };
import { buildAuthWelcomeEmailPrompt } from "./welcome-email/index.tpl.gen.js";
import type { AuthWelcomeEmailVariables } from "./welcome-email/index.tpl.gen.js";

/**
 * Auth onboarding sequence composed from folder-index prompts
 * @source src/features/auth/onboarding-sequence.tpl.md
 */
export interface AuthOnboardingSequenceVariables {
  userName: string;
  followUpDays: number;
  welcomeEmail: AuthWelcomeEmailVariables;
}

export function buildAuthOnboardingSequencePrompt(vars: AuthOnboardingSequenceVariables): string {
  return renderTemplate(TEMPLATE, { userName: vars.userName, followUpDays: vars.followUpDays }, { "welcomeEmail": buildAuthWelcomeEmailPrompt(vars.welcomeEmail) });
}
