/// <reference path="../../../lib/tpl.d.ts" />
// AUTO-GENERATED by tpl — do not edit
// Source: src/features/auth/password-reset.tpl.md
// Syntax:
//   {{var}}               required variable (string by default)
//   {{var:type}}          typed: string | number | boolean | string[]
//   {{var|default}}       optional — uses default when omitted
//   {{#if var}}...{{/if}} conditional block — condition-only vars are optional booleans
//   {{> ./path}}          relative partial — vars-less partials auto-render; vars partials become nested interface fields
// Docs: https://github.com/timurkr/tpl

import { renderTemplate } from "the-prompting-library/runtime";
import TEMPLATE from "./password-reset.tpl.md" with { type: "text" };
import { buildSharedBasePersonaPrompt } from "../../shared/base-persona.tpl.gen.js";

/**
 * Password reset email
 * @source src/features/auth/password-reset.tpl.md
 */
export interface AuthPasswordResetVariables {
  userName: string;
  expiryHours: string;
  productName: string;
}

export function buildAuthPasswordResetPrompt(vars: AuthPasswordResetVariables): string {
  return renderTemplate(TEMPLATE, vars, { "persona": buildSharedBasePersonaPrompt() });
}
