import { relative } from "path";
import type { ParsedTemplate, GenerateOptions } from "./types.js";
import { resolveIncludes } from "./resolver.js";

function toPascalCase(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function escapeTemplateLiteral(content: string): string {
  return content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

function buildFunctionBody(resolvedContent: string, variables: string[]): string {
  let escaped = escapeTemplateLiteral(resolvedContent);
  for (const variable of variables) {
    const pattern = new RegExp(`\\{\\{\\s*${variable}\\s*\\}\\}`, "g");
    escaped = escaped.replace(pattern, `\${vars.${variable}}`);
  }
  return escaped;
}

/** Generate the content for a single prompt file (e.g. welcome-email.ts). */
function generatePromptFile(
  template: ParsedTemplate,
  allTemplates: Map<string, ParsedTemplate>,
  rootDir: string
): string {
  const rawResolved = resolveIncludes(template, allTemplates);
  const resolved = rawResolved.replace(/\n{3,}/g, "\n\n").trim();
  const body = buildFunctionBody(resolved, template.variables);
  const { functionName, description, variables, filePath } = template;

  const relSource = relative(rootDir, filePath);
  const lines: string[] = [
    `// AUTO-GENERATED by tpl — do not edit`,
    `// Source: ${relSource}`,
    ``,
  ];

  const jsdocParts: string[] = [];
  if (description) jsdocParts.push(description);
  jsdocParts.push(`Source: ${relSource}`);
  lines.push(`/**`);
  for (const part of jsdocParts) lines.push(` * ${part}`);
  lines.push(` */`);

  if (variables.length > 0) {
    const interfaceName = `${toPascalCase(functionName)}Variables`;
    lines.push(`export interface ${interfaceName} {`);
    for (const v of variables) lines.push(`  ${v}: string;`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`export function ${functionName}(vars: ${interfaceName}): string {`);
  } else {
    lines.push(`export function ${functionName}(): string {`);
  }

  lines.push(`  return \`${body}\`;`);
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

/** Generate the index.ts that re-exports all prompts and defines the prompts const. */
function generateIndexFile(templates: ParsedTemplate[]): string {
  const timestamp = new Date().toISOString();
  const lines: string[] = [
    `// AUTO-GENERATED by tpl — do not edit`,
    `// Generated: ${timestamp} | ${templates.length} prompts`,
    ``,
  ];

  // Re-export everything from each prompt file
  for (const t of templates) {
    lines.push(`export * from "./${t.functionName}.js";`);
  }

  lines.push(``);

  // Import each function for the prompts const
  for (const t of templates) {
    lines.push(`import { ${t.functionName} } from "./${t.functionName}.js";`);
  }

  lines.push(``);
  lines.push(`export const prompts = {`);
  for (const t of templates) lines.push(`  ${t.functionName},`);
  lines.push(`} as const;`);
  lines.push(``);

  return lines.join("\n");
}

/**
 * Returns a Map of filename → file content for each prompt file plus an index.
 * Key is the bare filename, e.g. "welcome-email.ts" or "index.ts".
 */
export function generateFiles(
  templates: ParsedTemplate[],
  allTemplates: Map<string, ParsedTemplate>,
  options: GenerateOptions
): Map<string, string> {
  const nameToFiles = new Map<string, string[]>();
  for (const t of templates) {
    const existing = nameToFiles.get(t.functionName) ?? [];
    existing.push(t.filePath);
    nameToFiles.set(t.functionName, existing);
  }
  for (const [name, files] of nameToFiles) {
    if (files.length > 1) {
      throw new Error(
        `Name collision: multiple templates produce the function name '${name}':\n` +
          files.map((f) => `  - ${f}`).join("\n")
      );
    }
  }

  const out = new Map<string, string>();

  for (const template of templates) {
    const filename = `${template.functionName}.ts`;
    out.set(filename, generatePromptFile(template, allTemplates, options.rootDir));
  }

  out.set("index.ts", generateIndexFile(templates));

  return out;
}
