import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import fg from "fast-glob";
import { generateFiles } from "./codegen.js";
import { parseTemplate } from "./parser.js";
import type {
  CheckIssue,
  CheckResult,
  GenerateOptions,
  ParsedTemplate,
} from "./types.js";

const DEFAULT_PATTERN = "**/*.tpl.{md,mdx,txt,html}";
const DEFAULT_IGNORE = ["**/node_modules/**", "**/dist/**", "**/.git/**"];

function isTplGenerated(content: string): boolean {
  return content.includes("// AUTO-GENERATED by tpl");
}

export async function collect(
  options: GenerateOptions,
): Promise<ParsedTemplate[]> {
  const pattern = options.pattern ?? DEFAULT_PATTERN;
  const ignore = [...DEFAULT_IGNORE, ...(options.ignore ?? [])];

  const files = await fg(pattern, {
    cwd: options.rootDir,
    absolute: true,
    ignore,
  });

  return Promise.all(files.map((f) => parseTemplate(f, options.rootDir)));
}

export async function generate(
  options: GenerateOptions,
): Promise<{ outputFile: string; count: number; templates: ParsedTemplate[] }> {
  const templates = await collect(options);

  const allTemplates = new Map<string, ParsedTemplate>(
    templates.map((t) => [t.functionName, t]),
  );

  const files = generateFiles(templates, allTemplates, options);

  // Clean out stale colocated prompt files before writing so deleted prompts don't linger.
  const existingGenerated = await fg("**/*.tpl.gen.ts", {
    cwd: options.rootDir,
    absolute: true,
    ignore: [...DEFAULT_IGNORE, ...(options.ignore ?? [])],
  });
  const desiredPaths = new Set(files.keys());
  const existingAmbientDeclarations = await fg(
    ["**/tpl.d.ts", "**/tpl.gen.env.d.ts"],
    {
      cwd: options.rootDir,
      absolute: true,
      ignore: [...DEFAULT_IGNORE, ...(options.ignore ?? [])],
    },
  );
  await Promise.all(
    [...existingGenerated, ...existingAmbientDeclarations]
      .filter((filePath) => !desiredPaths.has(filePath))
      .map(async (filePath) => {
        const content = await readFile(filePath, "utf-8").catch(() => "");
        if (isTplGenerated(content)) {
          await rm(filePath, { force: true });
        }
      }),
  );

  // Write all generated files
  await Promise.all(
    Array.from(files.entries()).map(async ([filePath, content]) => {
      await mkdir(dirname(filePath), { recursive: true });
      await writeFile(filePath, content, "utf-8");
    }),
  );

  return { outputFile: options.outputFile, count: templates.length, templates };
}

export async function check(options: GenerateOptions): Promise<CheckResult> {
  const templates = await collect(options);

  const allTemplates = new Map<string, ParsedTemplate>(
    templates.map((t) => [t.functionName, t]),
  );

  const files = generateFiles(templates, allTemplates, options);
  const desiredPaths = new Set(files.keys());
  const issues: CheckIssue[] = [];

  await Promise.all(
    Array.from(files.entries()).map(async ([filePath, expected]) => {
      const actual = await readFile(filePath, "utf-8").catch(() => undefined);
      if (actual === undefined) {
        issues.push({ kind: "missing", filePath });
      } else if (actual !== expected) {
        issues.push({ kind: "changed", filePath });
      }
    }),
  );

  const existingGenerated = await fg("**/*.tpl.gen.ts", {
    cwd: options.rootDir,
    absolute: true,
    ignore: [...DEFAULT_IGNORE, ...(options.ignore ?? [])],
  });
  const existingAmbientDeclarations = await fg(
    ["**/tpl.d.ts", "**/tpl.gen.env.d.ts"],
    {
      cwd: options.rootDir,
      absolute: true,
      ignore: [...DEFAULT_IGNORE, ...(options.ignore ?? [])],
    },
  );

  await Promise.all(
    [...existingGenerated, ...existingAmbientDeclarations]
      .filter((filePath) => !desiredPaths.has(filePath))
      .map(async (filePath) => {
        const content = await readFile(filePath, "utf-8").catch(() => "");
        if (isTplGenerated(content)) {
          issues.push({ kind: "stale", filePath });
        }
      }),
  );

  issues.sort((a, b) =>
    a.filePath === b.filePath
      ? a.kind.localeCompare(b.kind)
      : a.filePath.localeCompare(b.filePath),
  );

  return {
    ok: issues.length === 0,
    outputFile: options.outputFile,
    count: templates.length,
    templates,
    issues,
  };
}
