/// <reference path="../../../../lib/tpl.d.ts" />
// AUTO-GENERATED by tpl — do not edit
// Source: src/features/auth/welcome-email/index.tpl.md
// Syntax:
//   {{var}}               required variable (string by default)
//   {{var:type}}          typed: string | number | boolean | string[]
//   {{var|default}}       optional — uses default when omitted
//   {{#if var}}...{{/if}} conditional block — condition-only vars are optional booleans
//   {{#switch v}}...{{/switch}} first matching {{#case "x"}} / {{#case 'x'}} / {{#case x}} ... {{/case}}, else {{#default}}...{{/default}}
//   {{> ./path}}          relative partial — vars-less partials auto-render; vars partials become nested interface fields
// Docs: https://github.com/timurkr/tpl

import { renderTemplate } from "the-prompting-library/runtime";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSharedBasePersonaPrompt } from "../../../shared/base-persona.tpl.gen.js";
import { buildAuthWelcomeEmailTonePrompt } from "./tone.tpl.gen.js";

const TEMPLATE = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "./index.tpl.md"), "utf8");

/**
 * Welcome email for new users
 * @source src/features/auth/welcome-email/index.tpl.md
 */
export interface AuthWelcomeEmailVariables {
  userName: string;
  productName: string;
  planType: string;
}

export function buildAuthWelcomeEmailPrompt(vars: AuthWelcomeEmailVariables): string {
  return renderTemplate(TEMPLATE, vars, { "persona": buildSharedBasePersonaPrompt(), "./tone": buildAuthWelcomeEmailTonePrompt() });
}
