/// <reference path="../../../../lib/tpl.d.ts" />
// AUTO-GENERATED by tpl — do not edit
// Source: src/features/auth/welcome-email/tone.tpl.md
// Syntax:
//   {{var}}               required variable (string by default)
//   {{var:type}}          typed: string | number | boolean | string[]
//   {{var|default}}       optional — uses default when omitted
//   {{#if var}}...{{/if}} conditional block — condition-only vars are optional booleans
//   {{#switch v}}...{{/switch}} first matching {{#case "x"}} / {{#case 'x'}} / {{#case x}} ... {{/case}}, else {{#default}}...{{/default}}
//   {{> ./path}}          relative partial — vars-less partials auto-render; vars partials become nested interface fields
// Docs: https://github.com/timurkr/tpl

import { renderTemplate } from "the-prompting-library/runtime";
import TEMPLATE from "./tone.tpl.md" with { type: "text" };

/**
 * @source src/features/auth/welcome-email/tone.tpl.md
 */
export interface AuthWelcomeEmailToneVariables {}

export function buildAuthWelcomeEmailTonePrompt(): string {
  return renderTemplate(TEMPLATE, {});
}
