import { describe, it, expect } from "bun:test";
import { generateFiles } from "../codegen.js";
import type { ParsedTemplate, VariableDef, GenerateOptions } from "../types.js";

const opts: GenerateOptions = {
  rootDir: "/project",
  outputDir: "/project/lib/tpl",
};

function varDef(
  name: string,
  overrides: Partial<VariableDef> = {}
): VariableDef {
  return { name, type: "string", optional: false, ...overrides };
}

function makeTemplate(
  overrides: Partial<ParsedTemplate> & { functionName: string }
): ParsedTemplate {
  return {
    filePath: `/project/${overrides.functionName}.tpl.md`,
    description: undefined,
    variables: [],
    includes: [],
    rawContent: "",
    ...overrides,
  };
}

function makeMap(templates: ParsedTemplate[]): Map<string, ParsedTemplate> {
  return new Map(templates.map((t) => [t.functionName, t]));
}

describe("generateFiles", () => {
  it("returns a file per prompt plus index.ts and tpl.d.ts", () => {
    const a = makeTemplate({ functionName: "foo", rawContent: "Foo" });
    const b = makeTemplate({ functionName: "bar", rawContent: "Bar" });
    const files = generateFiles([a, b], makeMap([a, b]), opts);
    expect(files.has("foo.ts")).toBe(true);
    expect(files.has("bar.ts")).toBe(true);
    expect(files.has("index.ts")).toBe(true);
    expect(files.has("tpl.d.ts")).toBe(true);
    // 2 prompt files + index.ts + tpl.d.ts
    expect(files.size).toBe(4);
  });

  it("index contains header comment with timestamp and count", () => {
    const t = makeTemplate({ functionName: "greeting", rawContent: "Hello" });
    const files = generateFiles([t], makeMap([t]), opts);
    const index = files.get("index.ts")!;
    expect(index).toContain("// AUTO-GENERATED by tpl — do not edit");
    expect(index).toContain("1 prompts");
  });

  it("prompt file contains AUTO-GENERATED header and syntax comment", () => {
    const t = makeTemplate({ functionName: "greeting", rawContent: "Hello" });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("greeting.ts")!;
    expect(prompt).toContain("// AUTO-GENERATED by tpl — do not edit");
    expect(prompt).toContain("// Syntax:");
  });

  it("prompt file imports renderTemplate from the-prompting-library/runtime", () => {
    const t = makeTemplate({ functionName: "greeting", rawContent: "Hello" });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("greeting.ts")!;
    expect(prompt).toContain(`import { renderTemplate } from "the-prompting-library/runtime"`);
  });

  it("function is named build<PascalName>Prompt", () => {
    const t = makeTemplate({ functionName: "welcomeEmail", rawContent: "Hello" });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("welcomeEmail.ts")!;
    expect(prompt).toContain("export function buildWelcomeEmailPrompt(");
  });

  it("generates interface with required string variable", () => {
    const t = makeTemplate({
      functionName: "welcomeEmail",
      variables: [varDef("userName"), varDef("productName")],
      rawContent: "Hello {{userName}} from {{productName}}",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("welcomeEmail.ts")!;
    expect(prompt).toContain("export interface WelcomeEmailVariables {");
    expect(prompt).toContain("  userName: string;");
    expect(prompt).toContain("  productName: string;");
  });

  it("generates optional field for variable with default", () => {
    const t = makeTemplate({
      functionName: "greet",
      variables: [varDef("name", { optional: true, defaultValue: "World" })],
      rawContent: "Hello {{name|World}}",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("greet.ts")!;
    expect(prompt).toContain("  name?: string;");
  });

  it("generates typed field for number variable", () => {
    const t = makeTemplate({
      functionName: "count",
      variables: [varDef("limit", { type: "number" })],
      rawContent: "Limit: {{limit:number}}",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("count.ts")!;
    expect(prompt).toContain("  limit: number;");
  });

  it("generates typed field for boolean variable", () => {
    const t = makeTemplate({
      functionName: "flag",
      variables: [varDef("active", { type: "boolean", optional: true })],
      rawContent: "{{#if active}}enabled{{/if}}",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("flag.ts")!;
    expect(prompt).toContain("  active?: boolean;");
  });

  it("generates typed field for string[] variable", () => {
    const t = makeTemplate({
      functionName: "list",
      variables: [varDef("tags", { type: "string[]" })],
      rawContent: "Tags: {{tags:string[]}}",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("list.ts")!;
    expect(prompt).toContain("  tags: string[];");
  });

  it("generates function using renderTemplate with vars parameter", () => {
    const t = makeTemplate({
      functionName: "greet",
      variables: [varDef("name")],
      rawContent: "Hello {{name}}",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("greet.ts")!;
    expect(prompt).toContain("buildGreetPrompt(vars: GreetVariables): string");
    expect(prompt).toContain("return renderTemplate(TEMPLATE, vars);");
  });

  it("always exports an interface, even when empty (no variables or includes)", () => {
    const t = makeTemplate({
      functionName: "staticPrompt",
      variables: [],
      rawContent: "You are a helpful assistant.",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("staticPrompt.ts")!;
    expect(prompt).toContain("export interface StaticPromptVariables {}");
    // Function still takes no params when there are no vars — empty interface is for the type only
    expect(prompt).toContain("export function buildStaticPromptPrompt(): string {");
    expect(prompt).not.toContain("(vars:");
  });

  it("imports the source .tpl.md file directly instead of inlining content", () => {
    const t = makeTemplate({
      functionName: "greet",
      filePath: "/project/src/greet.tpl.md",
      variables: [varDef("name")],
      rawContent: "Hello {{name}}",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("greet.ts")!;
    expect(prompt).toContain(`import TEMPLATE from "../../src/greet.tpl.md" with { type: "text" }`);
    expect(prompt).not.toContain("const TEMPLATE");
  });

  it("does not include a triple-slash reference directive", () => {
    const t = makeTemplate({ functionName: "greet", rawContent: "Hello" });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("greet.ts")!;
    expect(prompt).not.toContain(`/// <reference path`);
  });

  it("generates tpl.d.ts with ambient declarations for all supported extensions", () => {
    const t = makeTemplate({ functionName: "greet", rawContent: "Hello" });
    const files = generateFiles([t], makeMap([t]), opts);
    const dts = files.get("tpl.d.ts")!;
    expect(dts).toContain(`declare module "*.tpl.md"`);
    expect(dts).toContain(`declare module "*.tpl.mdx"`);
    expect(dts).toContain(`declare module "*.tpl.txt"`);
    expect(dts).toContain(`declare module "*.tpl.html"`);
    expect(dts).toContain(`export default content`);
  });

  it("template content is NOT inlined — no backtick escaping needed", () => {
    const t = makeTemplate({
      functionName: "ticked",
      variables: [],
      rawContent: "Use `backticks` and ${template} literals freely.",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("ticked.ts")!;
    // Content comes from the imported file at runtime — not escaped in the TS output
    expect(prompt).not.toContain("\\`backticks\\`");
    expect(prompt).not.toContain("\\${template}");
  });

  it("name collision: generates a single file with both templates + collision warning (no throw)", () => {
    const a = makeTemplate({ functionName: "greet", filePath: "/project/src/a/greet.tpl.md" });
    const b = makeTemplate({ functionName: "greet", filePath: "/project/src/b/greet.tpl.md" });
    // Must NOT throw — generation continues
    const files = generateFiles([a, b], makeMap([a, b]), opts);
    const file = files.get("greet.ts")!;
    expect(file).toBeDefined();
    expect(file).toContain("NAME COLLISION");
    expect(file).toContain("src/a/greet.tpl.md");
    expect(file).toContain("src/b/greet.tpl.md");
    // Both function bodies are present — duplicate declarations cause TypeScript errors
    expect(file.match(/export function buildGreetPrompt/g)?.length).toBe(2);
  });

  it("name collision: only one entry per name in index.ts", () => {
    const a = makeTemplate({ functionName: "greet", filePath: "/project/src/a/greet.tpl.md" });
    const b = makeTemplate({ functionName: "greet", filePath: "/project/src/b/greet.tpl.md" });
    const files = generateFiles([a, b], makeMap([a, b]), opts);
    const index = files.get("index.ts")!;
    // export * from "./greet.js" should appear exactly once
    expect(index.match(/export \* from "\.\/greet\.js"/g)?.length).toBe(1);
  });

  it("circular include: generates file with @ts-expect-error marker (no throw)", () => {
    const self = makeTemplate({
      functionName: "selfRef",
      filePath: "/project/selfRef.tpl.md",
      rawContent: "{{> selfRef}}",
      includes: ["selfRef"],
    });
    const map = makeMap([self]);
    // Must NOT throw — generation continues for other prompts
    const files = generateFiles([self], map, opts);
    const file = files.get("selfRef.ts")!;
    expect(file).toBeDefined();
    expect(file).toContain("CIRCULAR INCLUDE DETECTED");
    expect(file).toContain("@ts-expect-error");
    // The function is still exported so other code can reference it (TypeScript will error on the directive)
    expect(file).toContain("export function buildSelfRefPrompt");
  });

  it("index re-exports all prompts with export * using .js for Node16/NodeNext ESM", () => {
    const a = makeTemplate({ functionName: "foo", rawContent: "Foo" });
    const b = makeTemplate({ functionName: "bar", rawContent: "Bar" });
    const files = generateFiles([a, b], makeMap([a, b]), opts);
    const index = files.get("index.ts")!;
    expect(index).toContain(`export * from "./foo.js"`);
    expect(index).toContain(`export * from "./bar.js"`);
  });

  it("index imports build functions and defines prompts const with short keys", () => {
    const a = makeTemplate({ functionName: "foo", rawContent: "Foo" });
    const b = makeTemplate({ functionName: "bar", rawContent: "Bar" });
    const files = generateFiles([a, b], makeMap([a, b]), opts);
    const index = files.get("index.ts")!;
    expect(index).toContain(`import { buildFooPrompt } from "./foo.js"`);
    expect(index).toContain(`import { buildBarPrompt } from "./bar.js"`);
    expect(index).toContain("export const prompts = {");
    expect(index).toContain("  foo: buildFooPrompt,");
    expect(index).toContain("  bar: buildBarPrompt,");
  });

  it("index exports renderPrompt function", () => {
    const t = makeTemplate({ functionName: "greet", rawContent: "Hello" });
    const files = generateFiles([t], makeMap([t]), opts);
    const index = files.get("index.ts")!;
    expect(index).toContain("export function renderPrompt(");
    expect(index).toContain("name: keyof typeof prompts");
  });

  it("includes description in JSDoc when present", () => {
    const t = makeTemplate({
      functionName: "greet",
      description: "A greeting prompt",
      rawContent: "Hello",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("greet.ts")!;
    expect(prompt).toContain("A greeting prompt");
  });

  it("includes source path in JSDoc as relative path", () => {
    const t = makeTemplate({
      functionName: "greet",
      filePath: "/project/src/greet.tpl.md",
      rawContent: "Hello",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("greet.ts")!;
    expect(prompt).toContain("src/greet.tpl.md");
    expect(prompt).not.toContain("/project/src/greet.tpl.md");
  });

  it("partial with variables: exposed as nested field, build function called with vars.partialName", () => {
    const partial = makeTemplate({
      functionName: "footer",
      filePath: "/project/shared/footer.tpl.md",
      variables: [varDef("email"), varDef("phone")],
      rawContent: "Contact: {{email}} / {{phone}}",
    });
    const parent = makeTemplate({
      functionName: "welcome",
      variables: [varDef("userName")],
      includes: ["shared/footer"],
      rawContent: "Hi {{userName}}\n{{> shared/footer}}",
    });
    const map = makeMap([partial, parent]);
    const files = generateFiles([partial, parent], map, opts);
    const welcomeFile = files.get("welcome.ts")!;
    // Type and build fn imported
    expect(welcomeFile).toContain(`import { buildFooterPrompt } from "./footer.js"`);
    expect(welcomeFile).toContain(`import type { FooterVariables } from "./footer.js"`);
    // Exposed in interface
    expect(welcomeFile).toContain("  footer: FooterVariables;");
    expect(welcomeFile).toContain("  userName: string;");
    // Called with vars.footer
    expect(welcomeFile).toContain("footer: buildFooterPrompt(vars.footer)");
  });

  it("partial without variables: auto-rendered, not exposed in parent interface", () => {
    const partial = makeTemplate({
      functionName: "staticHeader",
      filePath: "/project/shared/static-header.tpl.md",
      variables: [],
      rawContent: "You are a helpful assistant.",
    });
    const parent = makeTemplate({
      functionName: "welcome",
      variables: [varDef("userName")],
      includes: ["shared/static-header"],
      rawContent: "{{> shared/static-header}}\nHi {{userName}}",
    });
    const map = makeMap([partial, parent]);
    const files = generateFiles([partial, parent], map, opts);
    const welcomeFile = files.get("welcome.ts")!;
    // Build fn imported (not the raw file)
    expect(welcomeFile).toContain(`import { buildStaticHeaderPrompt } from "./staticHeader.js"`);
    // NOT in the interface (not a field the caller provides)
    expect(welcomeFile).not.toContain("StaticHeaderVariables");
    // IS in the renderTemplate partials call (auto-rendered internally)
    expect(welcomeFile).toContain("staticHeader: buildStaticHeaderPrompt()");
    // Interface only has own vars
    expect(welcomeFile).toContain("  userName: string;");
  });

  it("count in index header matches number of templates", () => {
    const templates = [
      makeTemplate({ functionName: "a", rawContent: "A" }),
      makeTemplate({ functionName: "b", rawContent: "B" }),
      makeTemplate({ functionName: "c", rawContent: "C" }),
    ];
    const files = generateFiles(templates, makeMap(templates), opts);
    const index = files.get("index.ts")!;
    expect(index).toContain("3 prompts");
  });

  it("collision file: self-referencing template does not throw, still produces collision marker", () => {
    // generateCollisionFile called collectDirectPartialInfos bare, so a self-reference in any
    // colliding template would throw and escape generateFiles entirely — violating the no-throw contract.
    const selfRef = makeTemplate({
      functionName: "greet",
      filePath: "/project/src/a/greet.tpl.md",
      includes: ["greet"],
      rawContent: "{{> greet}}",
    });
    const other = makeTemplate({
      functionName: "greet",
      filePath: "/project/src/b/greet.tpl.md",
    });
    const map = makeMap([selfRef, other]);
    expect(() => generateFiles([selfRef, other], map, opts)).not.toThrow();
    const files = generateFiles([selfRef, other], map, opts);
    const file = files.get("greet.ts")!;
    expect(file).toBeDefined();
    expect(file).toContain("NAME COLLISION");
  });

  it("partial with vars: generated code does not pass full vars as first arg (prevents namespace pollution)", () => {
    // flattenVars recursively flattens nested objects, so passing the full vars
    // (which includes partial sub-objects like footer: { email, phone }) leaks those
    // keys into the parent template's substitution context. The fix is to pass
    // only own vars as the first arg when there are exposed partials.
    const partial = makeTemplate({
      functionName: "footer",
      filePath: "/project/shared/footer.tpl.md",
      variables: [varDef("email"), varDef("phone")],
      rawContent: "Contact: {{email}} / {{phone}}",
    });
    const parent = makeTemplate({
      functionName: "welcome",
      variables: [varDef("userName")],
      includes: ["shared/footer"],
      rawContent: "Hi {{userName}}\n{{> shared/footer}}",
    });
    const map = makeMap([partial, parent]);
    const files = generateFiles([partial, parent], map, opts);
    const welcomeFile = files.get("welcome.ts")!;
    // Must NOT pass full vars (which includes footer sub-object) as first arg
    expect(welcomeFile).not.toMatch(/renderTemplate\(TEMPLATE,\s*vars,/);
    // Must include own vars explicitly so only userName is in the flat substitution context
    expect(welcomeFile).toContain("userName: vars.userName");
  });
});
