import { describe, it, expect } from "bun:test";
import { generateFiles } from "../codegen.js";
import type { ParsedTemplate, GenerateOptions } from "../types.js";

const opts: GenerateOptions = {
  rootDir: "/project",
  outputDir: "/project/lib/tpl",
};

function makeTemplate(overrides: Partial<ParsedTemplate> & { functionName: string }): ParsedTemplate {
  return {
    filePath: `/project/${overrides.functionName}.tpl.md`,
    description: undefined,
    variables: [],
    includes: [],
    rawContent: "",
    ...overrides,
  };
}

function makeMap(templates: ParsedTemplate[]): Map<string, ParsedTemplate> {
  return new Map(templates.map((t) => [t.functionName, t]));
}

describe("generateFiles", () => {
  it("returns a file per prompt plus an index", () => {
    const a = makeTemplate({ functionName: "foo", rawContent: "Foo" });
    const b = makeTemplate({ functionName: "bar", rawContent: "Bar" });
    const files = generateFiles([a, b], makeMap([a, b]), opts);
    expect(files.has("foo.ts")).toBe(true);
    expect(files.has("bar.ts")).toBe(true);
    expect(files.has("index.ts")).toBe(true);
    expect(files.size).toBe(3);
  });

  it("index contains header comment with timestamp and count", () => {
    const t = makeTemplate({ functionName: "greeting", rawContent: "Hello" });
    const files = generateFiles([t], makeMap([t]), opts);
    const index = files.get("index.ts")!;
    expect(index).toContain("// AUTO-GENERATED by tpl — do not edit");
    expect(index).toContain("1 prompts");
  });

  it("prompt file contains AUTO-GENERATED header", () => {
    const t = makeTemplate({ functionName: "greeting", rawContent: "Hello" });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("greeting.ts")!;
    expect(prompt).toContain("// AUTO-GENERATED by tpl — do not edit");
  });

  it("generates interface for template with variables", () => {
    const t = makeTemplate({
      functionName: "welcomeEmail",
      variables: ["userName", "productName"],
      rawContent: "Hello {{userName}} from {{productName}}",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("welcomeEmail.ts")!;
    expect(prompt).toContain("export interface WelcomeEmailVariables {");
    expect(prompt).toContain("  userName: string;");
    expect(prompt).toContain("  productName: string;");
  });

  it("generates function with vars parameter when variables present", () => {
    const t = makeTemplate({
      functionName: "greet",
      variables: ["name"],
      rawContent: "Hello {{name}}",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("greet.ts")!;
    expect(prompt).toContain("export function greet(vars: GreetVariables): string {");
  });

  it("generates function with no parameters when no variables", () => {
    const t = makeTemplate({
      functionName: "staticPrompt",
      variables: [],
      rawContent: "You are a helpful assistant.",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("staticPrompt.ts")!;
    expect(prompt).toContain("export function staticPrompt(): string {");
    expect(prompt).not.toContain("vars:");
  });

  it("interpolates variables in template body", () => {
    const t = makeTemplate({
      functionName: "greet",
      variables: ["name"],
      rawContent: "Hello {{name}}",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("greet.ts")!;
    expect(prompt).toContain("${vars.name}");
    expect(prompt).not.toContain("{{name}}");
  });

  it("escapes backticks in template content", () => {
    const t = makeTemplate({
      functionName: "ticked",
      variables: [],
      rawContent: "Use `backticks` for code.",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("ticked.ts")!;
    expect(prompt).toContain("\\`backticks\\`");
  });

  it("escapes literal ${ in content", () => {
    const t = makeTemplate({
      functionName: "dollars",
      variables: [],
      rawContent: "The cost is ${price} in JS.",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("dollars.ts")!;
    expect(prompt).toContain("\\${price}");
  });

  it("throws on name collision", () => {
    const a = makeTemplate({ functionName: "greet", filePath: "/project/src/a/greet.tpl.md" });
    const b = makeTemplate({ functionName: "greet", filePath: "/project/src/b/greet.tpl.md" });
    expect(() => generateFiles([a, b], makeMap([a, b]), opts)).toThrow(/greet/);
    expect(() => generateFiles([a, b], makeMap([a, b]), opts)).toThrow(/src\/a\/greet\.tpl\.md/);
    expect(() => generateFiles([a, b], makeMap([a, b]), opts)).toThrow(/src\/b\/greet\.tpl\.md/);
  });

  it("index re-exports all prompts with export *", () => {
    const a = makeTemplate({ functionName: "foo", rawContent: "Foo" });
    const b = makeTemplate({ functionName: "bar", rawContent: "Bar" });
    const files = generateFiles([a, b], makeMap([a, b]), opts);
    const index = files.get("index.ts")!;
    expect(index).toContain(`export * from "./foo.js"`);
    expect(index).toContain(`export * from "./bar.js"`);
  });

  it("index imports and defines prompts const with all functions", () => {
    const a = makeTemplate({ functionName: "foo", rawContent: "Foo" });
    const b = makeTemplate({ functionName: "bar", rawContent: "Bar" });
    const files = generateFiles([a, b], makeMap([a, b]), opts);
    const index = files.get("index.ts")!;
    expect(index).toContain(`import { foo } from "./foo.js"`);
    expect(index).toContain(`import { bar } from "./bar.js"`);
    expect(index).toContain("export const prompts = {");
    expect(index).toContain("  foo,");
    expect(index).toContain("  bar,");
  });

  it("includes description in JSDoc when present", () => {
    const t = makeTemplate({
      functionName: "greet",
      description: "A greeting prompt",
      rawContent: "Hello",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("greet.ts")!;
    expect(prompt).toContain("A greeting prompt");
  });

  it("includes source path in JSDoc as relative path", () => {
    const t = makeTemplate({
      functionName: "greet",
      filePath: "/project/src/greet.tpl.md",
      rawContent: "Hello",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("greet.ts")!;
    expect(prompt).toContain("Source: src/greet.tpl.md");
    expect(prompt).not.toContain("Source: /project/src/greet.tpl.md");
  });

  it("handles multiple variables correctly", () => {
    const t = makeTemplate({
      functionName: "email",
      variables: ["to", "subject", "body"],
      rawContent: "To: {{to}}\nSubject: {{subject}}\n\n{{body}}",
    });
    const files = generateFiles([t], makeMap([t]), opts);
    const prompt = files.get("email.ts")!;
    expect(prompt).toContain("${vars.to}");
    expect(prompt).toContain("${vars.subject}");
    expect(prompt).toContain("${vars.body}");
  });

  it("count in index header matches number of templates", () => {
    const templates = [
      makeTemplate({ functionName: "a", rawContent: "A" }),
      makeTemplate({ functionName: "b", rawContent: "B" }),
      makeTemplate({ functionName: "c", rawContent: "C" }),
    ];
    const files = generateFiles(templates, makeMap(templates), opts);
    const index = files.get("index.ts")!;
    expect(index).toContain("3 prompts");
  });
});
