// AUTO-GENERATED by tpl — do not edit
// Source: src/features/support/ticket-classifier.tpl.md
// Syntax:
//   {{var}}               required variable (string by default)
//   {{var:type}}          typed: string | number | boolean | string[]
//   {{var|default}}       optional — uses default when omitted
//   {{#if var}}...{{/if}} conditional block — omitted when var is falsy
//   {{> name}}            partial — vars-less partials auto-render; vars partials become nested interface fields
// Docs: https://github.com/timurkr/tpl

import { renderTemplate } from "the-prompting-library/runtime";
import TEMPLATE from "./ticket-classifier.tpl.md" with { type: "text" };

/**
 * Support ticket classifier
 * @source src/features/support/ticket-classifier.tpl.md
 */
export interface TicketClassifierVariables {
  ticketContent: string;
  customerPlan: string;
}

export function buildTicketClassifierPrompt(vars: TicketClassifierVariables): string {
  return renderTemplate(TEMPLATE, vars);
}
