// AUTO-GENERATED by tpl — do not edit
// Ambient module declarations for .tpl.* source file imports.

declare module "*.tpl.md" { const content: string; export default content; }
declare module "*.tpl.mdx" { const content: string; export default content; }
declare module "*.tpl.txt" { const content: string; export default content; }
declare module "*.tpl.html" { const content: string; export default content; }
