/// <reference path="./tpl.d.ts" />
// AUTO-GENERATED by tpl — do not edit
// Generated manifest for 8 prompts

export * from "../src/features/auth/password-reset.tpl.gen.js";
export * from "../src/features/auth/welcome-email.tpl.gen.js";
export * from "../src/features/search/search-query.tpl.gen.js";
export * from "../src/features/support/ticket-classifier.tpl.gen.js";
export * from "../src/features/support/ticket-summary.tpl.gen.js";
export * from "../src/shared/assistant.tpl.gen.js";
export * from "../src/shared/base-persona.tpl.gen.js";
export * from "../src/shared/output-format.tpl.gen.js";

import { buildPasswordResetPrompt } from "../src/features/auth/password-reset.tpl.gen.js";
import { buildWelcomeEmailPrompt } from "../src/features/auth/welcome-email.tpl.gen.js";
import { buildSearchQueryPrompt } from "../src/features/search/search-query.tpl.gen.js";
import { buildTicketClassifierPrompt } from "../src/features/support/ticket-classifier.tpl.gen.js";
import { buildTicketSummaryPrompt } from "../src/features/support/ticket-summary.tpl.gen.js";
import { buildAssistantPrompt } from "../src/shared/assistant.tpl.gen.js";
import { buildBasePersonaPrompt } from "../src/shared/base-persona.tpl.gen.js";
import { buildOutputFormatPrompt } from "../src/shared/output-format.tpl.gen.js";

/**
 * All prompt builder functions, keyed by their short name.
 *
 * @example
 * import { prompts } from "./lib/tpl.gen.js";
 * const text = prompts.summarize({ topic: "AI", wordCount: "50" });
 */
export const prompts = {
  passwordReset: buildPasswordResetPrompt,
  welcomeEmail: buildWelcomeEmailPrompt,
  searchQuery: buildSearchQueryPrompt,
  ticketClassifier: buildTicketClassifierPrompt,
  ticketSummary: buildTicketSummaryPrompt,
  assistant: buildAssistantPrompt,
  basePersona: buildBasePersonaPrompt,
  outputFormat: buildOutputFormatPrompt,
} as const;

type PromptName = keyof typeof prompts;
type PromptArgs<Name extends PromptName> = Parameters<(typeof prompts)[Name]>;

/**
 * Render any prompt by name at runtime.
 * Useful when the template name comes from config or user input.
 *
 * @example
 * renderPrompt("summarize", { topic: "AI", wordCount: "50" });
 */
export function renderPrompt<Name extends PromptName>(
  name: Name,
  ...args: PromptArgs<Name>
): string {
  return (prompts[name] as (...args: PromptArgs<Name>) => string)(...args);
}
