// AUTO-GENERATED by tpl — do not edit
// Ambient module declarations for generated prompt files.

declare module "*.tpl.md" { const content: string; export default content; }
declare module "*.tpl.mdx" { const content: string; export default content; }
declare module "*.tpl.txt" { const content: string; export default content; }
declare module "*.tpl.html" { const content: string; export default content; }

declare module "node:fs" { export function readFileSync(path: string, encoding: "utf8"): string; }
declare module "node:path" { export function dirname(path: string): string; export function join(...paths: string[]): string; }
declare module "node:url" { export function fileURLToPath(url: string): string; }

interface ImportMeta { url: string; }
